POST {{host}}/admin/setRole
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM1ODY5NCwiZXhwIjoxNjE1MzYyMjk0fQ.N7d30DXS6sw9fZAwFws85GW8VxX9UiprUtVEVJZtjVE

{
  "adminPassword": "goga1234",
  "meil": "dato@gmail.com"
}

###
POST {{host}}/admin/users/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2MTUzMCwiZXhwIjoxNjE1MzY1MTMwfQ.SMaBkgJYx5_hE2g5L2p6-ysN4sFtigF4i_OpZmpdStk


###
POST {{host}}/admin/add/Lecture
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2OTcyMSwiZXhwIjoxNjE1MzczMzIxfQ.cvMUcHrSD8uvteYOKxdZqfFqRxBeJvQ3Vni3r2vEJYw

{
"time": "12:00",
  "lecturename": "Algebra",
  "roomname": "room1"
}



###
POST{{host}}/admin/add/room/room1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2OTcyMSwiZXhwIjoxNjE1MzczMzIxfQ.cvMUcHrSD8uvteYOKxdZqfFqRxBeJvQ3Vni3r2vEJYw

###
POST {{host}}/admin/lecture/add/student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2OTcyMSwiZXhwIjoxNjE1MzczMzIxfQ.cvMUcHrSD8uvteYOKxdZqfFqRxBeJvQ3Vni3r2vEJYw

{
  "gmail": "dato@gmail.com",
   "subject": "Algebra"
}

###
POST {{host}}/admin/lectures
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZGF0b0BnbWFpbC5jb20iLCJzdWIiOiJkYXRvQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM3MDQ4MSwiZXhwIjoxNjE1Mzc0MDgxfQ.FQXyH3Ztl66Ls2TB3K_GP0reHNbJiPUiM4iRATnJCsY

###
POST {{host}}/admin/lecture/change/2022-10-30T19:40:50.63/Algebra
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2MzU5MCwiZXhwIjoxNjE1MzY3MTkwfQ.JfOaduIIn1mlUyNu-vobgiMB24VpXLsoEH9dSez1RyQ


###
DELETE {{host}}/admin/delete/lecture/Algebra
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2ODU4MSwiZXhwIjoxNjE1MzcyMTgxfQ.5sTpQNNI5zkGjGy6r_PjWY9keX6-liAGkNB4acBJ2Ug

###
POST {{host}}/admin/room/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2MzU5MCwiZXhwIjoxNjE1MzY3MTkwfQ.JfOaduIIn1mlUyNu-vobgiMB24VpXLsoEH9dSez1RyQ


###
DELETE {{host}}/admin/room/delete/room1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2Mjg2MywiZXhwIjoxNjE1MzY2NDYzfQ.chyi6NHQxf8nVkunKtiOGp4NffQlzO0dwtVRGVUN780

###
POST {{host}}/admin/admins/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2ODU4MSwiZXhwIjoxNjE1MzcyMTgxfQ.5sTpQNNI5zkGjGy6r_PjWY9keX6-liAGkNB4acBJ2Ug

###
DELETE {{host}}/admin/delete/student/dato@gmail.com
Content-Type: application/json
Authorization: Berer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoiZ29nYUBnbWFpbC5jb20iLCJzdWIiOiJnb2dhQGdtYWlsLmNvbSIsImlhdCI6MTYxNTM2OTEwMywiZXhwIjoxNjE1MzcyNzAzfQ.T6Rt8mhIXHjHiv-1bObuUpLYEOEoz_P32EXmxLcl-TA

###
