POST {{host}}/api/v1/open/auth/sign-up
Content-Type: application/json

{
  "name": "goga",
  "lastname": "iremashvili",
  "username": "goga2000",
  "email": "goga@gmail.com",
  "password": "goga1234",
  "repassword": "goga1234",
  "your_id": "12312312312"
}

####


POST {{host}}/api/v1/open/auth/token
Content-Type: application/json

{
  "email": "goga@gmail.com",
  "password": "goga1234"
}





